default: &default
  adapter: mysql2
  encoding: utf8mb4
  # db
  host: <%= ENV['MYSQL_HOST'] %>
  # 3306
  port: <%= ENV['MYSQL_PORT'] %>
  # root
  username: <%= ENV['MYSQL_USER'] %>
  # password
  password: <%= ENV['MYSQL_PASSWORD'] %>

development:
  <<: *default
  database: presto_development

test:
  <<: *default
  database: presto_test

production:
  <<: *default
  database: presto_production
  username: backend
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
